template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mldemo_mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mldemo_mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: marcus_demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          inputResources:
            - name: mldemo_mvn_repo
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mldemo_mvn_build_info
